package core

import (
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/mattn/anko/vm"
)

func TestToX(t *testing.T) {
	os.Setenv("ANKO_DEBUG", "1")
	tests := []vm.Test{
		{Script: `toBool(-2)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool(-1.5)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool(-1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool(-0.4)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool(0)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool(0.4)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: true},
		{Script: `toBool(1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: true},
		{Script: `toBool(1.5)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: true},
		{Script: `toBool(2)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: true},
		{Script: `toBool(true)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: true},
		{Script: `toBool(false)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool("true")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: true},
		{Script: `toBool("false")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool("yes")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: true},
		{Script: `toBool("ye")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool("y")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: true},
		{Script: `toBool("false")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool("f")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool("")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool(nil)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool({})`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool([])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool([true])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toBool({"true": "true"})`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: false},
		{Script: `toString(nil)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "<nil>"},
		{Script: `toString("")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: ""},
		{Script: `toString(1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "1"},
		{Script: `toString(1.2)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "1.2"},
		{Script: `toString(1/3)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "0.3333333333333333"},
		{Script: `toString(false)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "false"},
		{Script: `toString(true)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "true"},
		{Script: `toString({})`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "map[]"},
		{Script: `toString({"foo": "bar"})`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "map[foo:bar]"},
		{Script: `toString([true,nil])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "[true <nil>]"},
		{Script: `toString(toByteSlice("foo"))`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "foo"},
		{Script: `toInt(nil)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(0)},
		{Script: `toInt(-2)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(-2)},
		{Script: `toInt(-1.4)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(-1)},
		{Script: `toInt(-1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(-1)},
		{Script: `toInt(0)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(0)},
		{Script: `toInt(1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(1)},
		{Script: `toInt(1.4)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(1)},
		{Script: `toInt(1.5)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(1)},
		{Script: `toInt(1.9)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(1)},
		{Script: `toInt(2)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(2)},
		{Script: `toInt(2.1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(2)},
		{Script: `toInt("2")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(2)},
		{Script: `toInt("2.1")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(2)},
		{Script: `toInt(true)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(1)},
		{Script: `toInt(false)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(0)},
		{Script: `toInt({})`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(0)},
		{Script: `toInt([])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: int64(0)},
		{Script: `toFloat(nil)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(0.0)},
		{Script: `toFloat(-2)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(-2.0)},
		{Script: `toFloat(-1.4)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(-1.4)},
		{Script: `toFloat(-1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(-1.0)},
		{Script: `toFloat(0)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(0.0)},
		{Script: `toFloat(1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(1.0)},
		{Script: `toFloat(1.4)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(1.4)},
		{Script: `toFloat(1.5)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(1.5)},
		{Script: `toFloat(1.9)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(1.9)},
		{Script: `toFloat(2)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(2.0)},
		{Script: `toFloat(2.1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(2.1)},
		{Script: `toFloat("2")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(2.0)},
		{Script: `toFloat("2.1")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(2.1)},
		{Script: `toFloat(true)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(1.0)},
		{Script: `toFloat(false)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(0.0)},
		{Script: `toFloat({})`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(0.0)},
		{Script: `toFloat([])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: float64(0.0)},
		{Script: `toChar(0x1F431)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "🐱"},
		{Script: `toChar(0)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: "\x00"},
		{Script: `toRune("")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: rune(0)},
		{Script: `toRune("🐱")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: rune(0x1F431)},
		{Script: `toBoolSlice(nil)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []bool{}},
		{Script: `toBoolSlice(1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type int64")},
		{Script: `toBoolSlice(1.2)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type float64")},
		{Script: `toBoolSlice(false)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type bool")},
		{Script: `toBoolSlice({})`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type map[string]interface {}")},
		{Script: `toBoolSlice([])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []bool{}},
		{Script: `toBoolSlice([nil])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []bool{false}},
		{Script: `toBoolSlice([1])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []bool{false}},
		{Script: `toBoolSlice([1.1])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []bool{false}},
		{Script: `toBoolSlice([true])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []bool{true}},
		{Script: `toBoolSlice([[]])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []bool{false}},
		{Script: `toBoolSlice([{}])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []bool{false}},
		{Script: `toIntSlice(nil)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []int64{}},
		{Script: `toIntSlice(1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type int64")},
		{Script: `toIntSlice(1.2)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type float64")},
		{Script: `toIntSlice(false)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type bool")},
		{Script: `toIntSlice({})`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type map[string]interface {}")},
		{Script: `toIntSlice([])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []int64{}},
		{Script: `toIntSlice([nil])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []int64{0}},
		{Script: `toIntSlice([1])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []int64{1}},
		{Script: `toIntSlice([1.1])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []int64{1}},
		{Script: `toIntSlice([true])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []int64{0}},
		{Script: `toIntSlice([[]])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []int64{0}},
		{Script: `toIntSlice([{}])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []int64{0}},
		{Script: `toFloatSlice(nil)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []float64{}},
		{Script: `toFloatSlice(1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type int64")},
		{Script: `toFloatSlice(1.2)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type float64")},
		{Script: `toFloatSlice(false)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type bool")},
		{Script: `toFloatSlice({})`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type []interface {} but received type map[string]interface {}")},
		{Script: `toFloatSlice([])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []float64{}},
		{Script: `toFloatSlice([nil])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []float64{0.0}},
		{Script: `toFloatSlice([1])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []float64{1.0}},
		{Script: `toFloatSlice([1.1])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []float64{1.1}},
		{Script: `toFloatSlice([true])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []float64{0.0}},
		{Script: `toFloatSlice([[]])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []float64{0.0}},
		{Script: `toFloatSlice([{}])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []float64{0.0}},
		{Script: `toByteSlice(nil)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []byte{}},
		{Script: `toByteSlice([])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type string but received type []interface {}")},
		{Script: `toByteSlice(1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []byte{0x01}}, // FIXME?
		{Script: `toByteSlice(1.1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type string but received type float64")},
		{Script: `toByteSlice(true)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type string but received type bool")},
		{Script: `toByteSlice("foo")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []byte{'f', 'o', 'o'}},
		{Script: `toByteSlice("世界")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []byte{0xe4, 0xb8, 0x96, 0xe7, 0x95, 0x8c}},
		{Script: `toRuneSlice(nil)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []rune{}},
		{Script: `toRuneSlice([])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type string but received type []interface {}")},
		{Script: `toRuneSlice(1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []rune{0x01}}, // FIXME?
		{Script: `toRuneSlice(1.1)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type string but received type float64")},
		{Script: `toRuneSlice(true)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type string but received type bool")},
		{Script: `toRuneSlice("foo")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []rune{'f', 'o', 'o'}},
		{Script: `toRuneSlice("世界")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []rune{'世', '界'}},
		{Script: `toStringSlice([true,false,1])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: []string{"", "", "\x01"}}, // FIXME?
		{Script: `toDuration(nil)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: time.Duration(0)},
		{Script: `toDuration(0)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunOutput: time.Duration(0)},
		{Script: `toDuration(true)`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type int64 but received type bool")},
		{Script: `toDuration([])`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type int64 but received type []interface {}")},
		{Script: `toDuration({})`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type int64 but received type map[string]interface {}")},
		{Script: `toDuration("")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type int64 but received type string")},
		{Script: `toDuration("1s")`, EnvSetupFunc: &testCoreEnvSetupFunc, RunError: fmt.Errorf("function wants argument type int64 but received type string")}, // TODO
		{Script: `toDuration(a)`, EnvSetupFunc: &testCoreEnvSetupFunc, Input: map[string]interface{}{"a": int64(time.Duration(123 * time.Minute))}, RunOutput: time.Duration(123 * time.Minute)},
		{Script: `toDuration(a)`, EnvSetupFunc: &testCoreEnvSetupFunc, Input: map[string]interface{}{"a": float64(time.Duration(123 * time.Minute))}, RunOutput: time.Duration(123 * time.Minute)},
		{Script: `toDuration(a)`, EnvSetupFunc: &testCoreEnvSetupFunc, Input: map[string]interface{}{"a": time.Duration(123 * time.Minute)}, RunOutput: time.Duration(123 * time.Minute)},
	}
	vm.RunTests(t, tests)
}
