// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package parser

import __yyfmt__ "fmt"

//line parser.go.y:2

import (
	"github.com/mattn/anko/ast"
)

//line parser.go.y:40
type yySymType struct {
	yys                 int
	compstmt            ast.Stmt
	stmt_var_or_lets    ast.Stmt
	stmt_var            ast.Stmt
	stmt_lets           ast.Stmt
	stmt_if             ast.Stmt
	stmt_for            ast.Stmt
	stmt_switch         ast.Stmt
	stmt_switch_cases   ast.Stmt
	stmt_switch_case    ast.Stmt
	stmt_switch_default ast.Stmt
	stmts               ast.Stmt
	stmt                ast.Stmt
	exprs               []ast.Expr
	expr                ast.Expr
	map_expr            map[ast.Expr]ast.Expr
	expr_idents         []string
	expr_literals       ast.Expr
	expr_type           string
	tok                 ast.Token
	array_count         ast.ArrayCount
	expr_slice          ast.Expr
	expr_ident          ast.Expr
	expr_op             ast.Expr
	expr_unary          ast.Expr
	expr_binary         ast.Expr
	expr_lets           ast.Expr
	op_binary           ast.Operator
	op_comparison       ast.Operator
	op_add              ast.Operator
	op_multiply         ast.Operator
}

const IDENT = 57346
const NUMBER = 57347
const STRING = 57348
const ARRAY = 57349
const VARARG = 57350
const FUNC = 57351
const RETURN = 57352
const VAR = 57353
const THROW = 57354
const IF = 57355
const ELSE = 57356
const FOR = 57357
const IN = 57358
const EQEQ = 57359
const NEQ = 57360
const GE = 57361
const LE = 57362
const OROR = 57363
const ANDAND = 57364
const NEW = 57365
const TRUE = 57366
const FALSE = 57367
const NIL = 57368
const NILCOALESCE = 57369
const MODULE = 57370
const TRY = 57371
const CATCH = 57372
const FINALLY = 57373
const PLUSEQ = 57374
const MINUSEQ = 57375
const MULEQ = 57376
const DIVEQ = 57377
const ANDEQ = 57378
const OREQ = 57379
const BREAK = 57380
const CONTINUE = 57381
const PLUSPLUS = 57382
const MINUSMINUS = 57383
const POW = 57384
const SHIFTLEFT = 57385
const SHIFTRIGHT = 57386
const SWITCH = 57387
const CASE = 57388
const DEFAULT = 57389
const GO = 57390
const CHAN = 57391
const MAKE = 57392
const OPCHAN = 57393
const TYPE = 57394
const LEN = 57395
const DELETE = 57396
const CLOSE = 57397
const UNARY = 57398

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"NUMBER",
	"STRING",
	"ARRAY",
	"VARARG",
	"FUNC",
	"RETURN",
	"VAR",
	"THROW",
	"IF",
	"ELSE",
	"FOR",
	"IN",
	"EQEQ",
	"NEQ",
	"GE",
	"LE",
	"OROR",
	"ANDAND",
	"NEW",
	"TRUE",
	"FALSE",
	"NIL",
	"NILCOALESCE",
	"MODULE",
	"TRY",
	"CATCH",
	"FINALLY",
	"PLUSEQ",
	"MINUSEQ",
	"MULEQ",
	"DIVEQ",
	"ANDEQ",
	"OREQ",
	"BREAK",
	"CONTINUE",
	"PLUSPLUS",
	"MINUSMINUS",
	"POW",
	"SHIFTLEFT",
	"SHIFTRIGHT",
	"SWITCH",
	"CASE",
	"DEFAULT",
	"GO",
	"CHAN",
	"MAKE",
	"OPCHAN",
	"TYPE",
	"LEN",
	"DELETE",
	"CLOSE",
	"'='",
	"':'",
	"'?'",
	"'<'",
	"'>'",
	"'+'",
	"'-'",
	"'|'",
	"'^'",
	"'*'",
	"'/'",
	"'%'",
	"'&'",
	"UNARY",
	"'{'",
	"'}'",
	"'('",
	"')'",
	"';'",
	"'['",
	"']'",
	"','",
	"'.'",
	"'!'",
	"'\\n'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.go.y:960

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	56, 70,
	74, 5,
	77, 70,
	-2, 1,
	-1, 22,
	77, 71,
	-2, 24,
	-1, 26,
	56, 70,
	-2, 59,
	-1, 62,
	56, 70,
	77, 70,
	-2, 5,
	-1, 114,
	16, 60,
	77, 60,
	-2, 107,
	-1, 136,
	1, 119,
	8, 119,
	46, 119,
	47, 119,
	56, 119,
	57, 119,
	70, 119,
	71, 119,
	73, 119,
	74, 119,
	76, 119,
	77, 119,
	80, 119,
	-2, 74,
	-1, 138,
	1, 121,
	8, 121,
	46, 121,
	47, 121,
	56, 121,
	57, 121,
	70, 121,
	71, 121,
	73, 121,
	74, 121,
	76, 121,
	77, 121,
	80, 121,
	-2, 74,
	-1, 243,
	76, 166,
	-2, 158,
	-1, 246,
	71, 166,
	-2, 158,
	-1, 263,
	1, 73,
	8, 73,
	46, 73,
	47, 73,
	56, 73,
	57, 73,
	71, 73,
	73, 73,
	74, 73,
	76, 73,
	77, 73,
	80, 73,
	-2, 74,
	-1, 264,
	1, 120,
	8, 120,
	46, 120,
	47, 120,
	56, 120,
	57, 120,
	70, 120,
	71, 120,
	73, 120,
	74, 120,
	76, 120,
	77, 120,
	80, 120,
	-2, 78,
	-1, 265,
	1, 122,
	8, 122,
	46, 122,
	47, 122,
	56, 122,
	57, 122,
	70, 122,
	71, 122,
	73, 122,
	74, 122,
	76, 122,
	77, 122,
	80, 122,
	-2, 78,
	-1, 271,
	1, 20,
	46, 20,
	47, 20,
	71, 20,
	74, 20,
	80, 20,
	-2, 87,
	-1, 273,
	1, 22,
	46, 22,
	47, 22,
	71, 22,
	74, 22,
	80, 22,
	-2, 89,
	-1, 302,
	71, 164,
	76, 164,
	-2, 159,
	-1, 319,
	1, 19,
	46, 19,
	47, 19,
	71, 19,
	74, 19,
	80, 19,
	-2, 86,
	-1, 320,
	1, 21,
	46, 21,
	47, 21,
	71, 21,
	74, 21,
	80, 21,
	-2, 88,
}

const yyPrivate = 57344

const yyLast = 3487

var yyAct = [...]int{

	66, 291, 292, 22, 28, 201, 244, 7, 8, 110,
	208, 81, 131, 1, 64, 67, 6, 294, 293, 5,
	246, 72, 63, 8, 253, 8, 108, 111, 115, 252,
	43, 185, 121, 132, 122, 82, 83, 132, 243, 361,
	127, 8, 314, 311, 65, 80, 80, 116, 120, 120,
	303, 8, 129, 133, 134, 135, 137, 139, 189, 132,
	136, 138, 258, 22, 119, 301, 79, 79, 272, 75,
	75, 64, 78, 78, 147, 148, 149, 151, 152, 270,
	184, 155, 156, 341, 144, 157, 158, 159, 160, 161,
	162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
	172, 173, 174, 175, 176, 177, 178, 179, 180, 249,
	154, 312, 202, 188, 309, 313, 252, 191, 310, 252,
	320, 203, 197, 182, 205, 200, 183, 193, 64, 207,
	300, 319, 241, 273, 185, 307, 299, 132, 278, 194,
	118, 185, 123, 214, 271, 145, 128, 206, 132, 120,
	195, 222, 126, 125, 199, 213, 124, 215, 73, 395,
	224, 394, 209, 387, 386, 210, 384, 380, 379, 375,
	374, 373, 389, 372, 250, 362, 217, 218, 132, 142,
	358, 354, 352, 255, 351, 228, 350, 347, 232, 323,
	235, 64, 317, 239, 305, 226, 282, 240, 279, 268,
	230, 185, 120, 247, 242, 266, 227, 120, 117, 254,
	256, 262, 245, 245, 216, 263, 81, 391, 229, 390,
	365, 274, 9, 236, 277, 225, 348, 340, 339, 132,
	298, 141, 70, 334, 286, 288, 143, 385, 295, 261,
	82, 83, 107, 104, 105, 283, 269, 10, 183, 306,
	69, 80, 308, 64, 294, 293, 281, 265, 318, 264,
	302, 315, 257, 302, 202, 101, 102, 103, 106, 130,
	153, 68, 79, 4, 113, 75, 210, 62, 78, 304,
	2, 316, 57, 58, 61, 140, 59, 60, 51, 50,
	330, 49, 333, 332, 322, 335, 41, 35, 324, 325,
	204, 327, 183, 29, 183, 342, 196, 120, 290, 19,
	64, 343, 338, 17, 344, 345, 16, 24, 23, 3,
	0, 0, 0, 331, 0, 336, 0, 0, 0, 0,
	0, 0, 349, 0, 0, 0, 0, 0, 0, 0,
	353, 0, 355, 356, 0, 0, 183, 0, 359, 0,
	0, 0, 0, 363, 364, 0, 0, 0, 0, 0,
	0, 0, 371, 0, 0, 0, 0, 382, 0, 0,
	383, 376, 0, 0, 377, 378, 0, 0, 0, 381,
	0, 0, 81, 92, 93, 97, 95, 91, 90, 0,
	0, 0, 0, 77, 0, 0, 0, 0, 84, 85,
	87, 88, 89, 86, 392, 393, 82, 83, 107, 104,
	105, 0, 0, 0, 0, 0, 0, 80, 0, 0,
	0, 0, 0, 0, 76, 94, 96, 98, 99, 100,
	0, 101, 102, 103, 106, 0, 0, 0, 79, 368,
	0, 75, 0, 369, 78, 81, 92, 93, 97, 95,
	91, 90, 0, 0, 0, 0, 77, 0, 0, 0,
	0, 84, 85, 87, 88, 89, 86, 0, 0, 82,
	83, 107, 104, 105, 0, 0, 0, 0, 0, 0,
	80, 0, 0, 0, 0, 0, 0, 76, 94, 96,
	98, 99, 100, 0, 101, 102, 103, 106, 0, 0,
	0, 79, 259, 0, 75, 0, 260, 78, 81, 92,
	93, 97, 95, 91, 90, 0, 0, 0, 0, 77,
	0, 0, 0, 0, 84, 85, 87, 88, 89, 86,
	0, 0, 82, 83, 107, 104, 105, 0, 0, 0,
	0, 0, 0, 80, 0, 0, 0, 0, 0, 237,
	76, 94, 96, 98, 99, 100, 0, 101, 102, 103,
	106, 0, 0, 0, 79, 0, 0, 75, 238, 0,
	78, 81, 92, 93, 97, 95, 91, 90, 0, 0,
	0, 0, 77, 0, 0, 0, 0, 84, 85, 87,
	88, 89, 86, 0, 0, 82, 83, 107, 104, 105,
	0, 0, 0, 0, 0, 0, 80, 0, 0, 0,
	0, 0, 220, 76, 94, 96, 98, 99, 100, 0,
	101, 102, 103, 106, 0, 0, 0, 79, 0, 0,
	75, 221, 0, 78, 81, 92, 93, 97, 95, 91,
	90, 0, 0, 0, 0, 77, 0, 0, 0, 0,
	84, 85, 87, 88, 89, 86, 0, 0, 82, 83,
	107, 104, 105, 0, 0, 0, 0, 0, 0, 80,
	0, 0, 0, 0, 74, 0, 76, 94, 96, 98,
	99, 100, 0, 101, 102, 103, 106, 0, 186, 0,
	79, 0, 0, 75, 0, 0, 78, 81, 92, 93,
	97, 95, 91, 90, 0, 0, 0, 0, 77, 0,
	0, 0, 0, 84, 85, 87, 88, 89, 86, 0,
	0, 82, 83, 107, 104, 105, 0, 0, 0, 0,
	0, 0, 80, 0, 0, 0, 0, 0, 0, 76,
	94, 96, 98, 99, 100, 0, 101, 102, 103, 106,
	0, 0, 0, 79, 388, 0, 75, 0, 0, 78,
	81, 92, 93, 97, 95, 91, 90, 0, 0, 0,
	0, 77, 0, 0, 0, 0, 84, 85, 87, 88,
	89, 86, 0, 0, 82, 83, 107, 104, 105, 0,
	0, 0, 0, 0, 0, 80, 0, 0, 0, 0,
	0, 0, 76, 94, 96, 98, 99, 100, 0, 101,
	102, 103, 106, 0, 0, 0, 79, 370, 0, 75,
	0, 0, 78, 81, 92, 93, 97, 95, 91, 90,
	0, 0, 0, 0, 77, 0, 0, 0, 0, 84,
	85, 87, 88, 89, 86, 0, 0, 82, 83, 107,
	104, 105, 0, 0, 0, 0, 0, 0, 80, 0,
	0, 0, 0, 0, 0, 76, 94, 96, 98, 99,
	100, 0, 101, 102, 103, 106, 0, 0, 0, 79,
	367, 0, 75, 0, 0, 78, 81, 92, 93, 97,
	95, 91, 90, 0, 0, 0, 0, 77, 0, 0,
	0, 0, 84, 85, 87, 88, 89, 86, 0, 0,
	82, 83, 107, 104, 105, 0, 0, 0, 0, 0,
	0, 80, 0, 0, 0, 0, 0, 366, 76, 94,
	96, 98, 99, 100, 0, 101, 102, 103, 106, 0,
	0, 0, 79, 0, 0, 75, 0, 0, 78, 81,
	92, 93, 97, 95, 91, 90, 0, 0, 0, 0,
	77, 0, 0, 0, 0, 84, 85, 87, 88, 89,
	86, 0, 0, 82, 83, 107, 104, 105, 0, 0,
	0, 0, 0, 0, 80, 0, 0, 0, 0, 0,
	360, 76, 94, 96, 98, 99, 100, 0, 101, 102,
	103, 106, 0, 0, 0, 79, 0, 0, 75, 0,
	0, 78, 81, 92, 93, 97, 95, 91, 90, 0,
	0, 0, 0, 77, 0, 0, 0, 0, 84, 85,
	87, 88, 89, 86, 0, 0, 82, 83, 107, 104,
	105, 0, 0, 0, 0, 0, 0, 80, 0, 0,
	0, 0, 0, 0, 76, 94, 96, 98, 99, 100,
	0, 101, 102, 103, 106, 0, 357, 0, 79, 0,
	0, 75, 0, 0, 78, 81, 92, 93, 97, 95,
	91, 90, 0, 0, 0, 0, 77, 0, 0, 0,
	0, 84, 85, 87, 88, 89, 86, 0, 0, 82,
	83, 107, 104, 105, 0, 0, 0, 0, 0, 0,
	80, 0, 0, 0, 0, 0, 0, 76, 94, 96,
	98, 99, 100, 0, 101, 102, 103, 106, 0, 0,
	0, 79, 346, 0, 75, 0, 0, 78, 81, 92,
	93, 97, 95, 91, 90, 0, 0, 0, 0, 77,
	0, 0, 0, 0, 84, 85, 87, 88, 89, 86,
	0, 0, 82, 83, 107, 104, 105, 0, 0, 0,
	0, 0, 0, 80, 0, 0, 0, 0, 0, 0,
	76, 94, 96, 98, 99, 100, 0, 101, 102, 103,
	106, 0, 0, 0, 79, 0, 0, 75, 337, 0,
	78, 81, 92, 93, 97, 95, 91, 90, 0, 0,
	0, 0, 77, 0, 0, 0, 0, 84, 85, 87,
	88, 89, 86, 0, 0, 82, 83, 107, 104, 105,
	0, 0, 0, 0, 0, 0, 80, 0, 0, 0,
	0, 0, 0, 76, 94, 96, 98, 99, 100, 0,
	101, 102, 103, 106, 0, 328, 0, 79, 0, 0,
	75, 0, 0, 78, 81, 92, 93, 97, 95, 91,
	90, 0, 0, 0, 0, 77, 0, 0, 0, 0,
	84, 85, 87, 88, 89, 86, 0, 0, 82, 83,
	107, 104, 105, 0, 0, 0, 0, 0, 0, 80,
	0, 0, 0, 0, 0, 0, 76, 94, 96, 98,
	99, 100, 0, 101, 102, 103, 106, 0, 326, 0,
	79, 0, 0, 75, 0, 0, 78, 81, 92, 93,
	97, 95, 91, 90, 0, 0, 0, 0, 77, 0,
	0, 0, 0, 84, 85, 87, 88, 89, 86, 0,
	0, 82, 83, 107, 104, 105, 0, 0, 0, 0,
	0, 0, 80, 0, 0, 0, 0, 0, 0, 76,
	94, 96, 98, 99, 100, 0, 101, 102, 103, 106,
	0, 0, 0, 79, 0, 0, 75, 321, 0, 78,
	81, 92, 93, 97, 95, 91, 90, 0, 0, 0,
	0, 77, 0, 0, 0, 0, 84, 85, 87, 88,
	89, 86, 0, 0, 82, 83, 107, 104, 105, 0,
	0, 0, 0, 0, 0, 80, 0, 0, 0, 0,
	0, 0, 76, 94, 96, 98, 99, 100, 0, 101,
	102, 103, 106, 0, 0, 0, 79, 0, 0, 75,
	297, 0, 78, 81, 92, 93, 97, 95, 91, 90,
	0, 0, 0, 0, 77, 0, 0, 0, 0, 84,
	85, 87, 88, 89, 86, 0, 0, 82, 83, 107,
	104, 105, 0, 0, 0, 0, 0, 0, 80, 0,
	0, 0, 0, 0, 0, 76, 94, 96, 98, 99,
	100, 0, 101, 102, 103, 106, 0, 0, 0, 79,
	0, 289, 75, 0, 0, 78, 81, 92, 93, 97,
	95, 91, 90, 0, 0, 0, 0, 77, 0, 0,
	0, 0, 84, 85, 87, 88, 89, 86, 0, 0,
	82, 83, 107, 104, 105, 0, 0, 0, 0, 0,
	0, 80, 0, 0, 0, 0, 0, 0, 76, 94,
	96, 98, 99, 100, 0, 101, 102, 103, 106, 0,
	284, 0, 79, 0, 0, 75, 0, 0, 78, 81,
	92, 93, 97, 95, 91, 90, 0, 0, 0, 0,
	77, 0, 0, 0, 0, 84, 85, 87, 88, 89,
	86, 0, 0, 82, 83, 107, 104, 105, 0, 0,
	0, 0, 0, 0, 80, 0, 0, 0, 0, 0,
	0, 76, 94, 96, 98, 99, 100, 0, 101, 102,
	103, 106, 0, 280, 0, 79, 0, 0, 75, 0,
	0, 78, 81, 92, 93, 97, 95, 91, 90, 0,
	0, 0, 0, 77, 0, 0, 0, 0, 84, 85,
	87, 88, 89, 86, 0, 0, 82, 83, 107, 104,
	105, 0, 0, 0, 0, 0, 0, 80, 0, 0,
	0, 0, 0, 0, 76, 94, 96, 98, 99, 100,
	0, 101, 102, 103, 106, 0, 0, 0, 79, 0,
	0, 75, 276, 0, 78, 81, 92, 93, 97, 95,
	91, 90, 0, 0, 0, 0, 77, 0, 0, 0,
	0, 84, 85, 87, 88, 89, 86, 0, 0, 82,
	83, 107, 104, 105, 0, 0, 0, 0, 0, 0,
	80, 0, 0, 0, 0, 0, 0, 76, 94, 96,
	98, 99, 100, 0, 101, 102, 103, 106, 0, 267,
	0, 79, 0, 0, 75, 0, 0, 78, 81, 92,
	93, 97, 95, 91, 90, 0, 0, 0, 0, 77,
	0, 0, 0, 0, 84, 85, 87, 88, 89, 86,
	0, 0, 82, 83, 107, 104, 105, 0, 0, 0,
	0, 0, 0, 80, 0, 0, 0, 0, 0, 0,
	76, 94, 96, 98, 99, 100, 0, 101, 102, 103,
	106, 0, 0, 0, 79, 251, 0, 75, 0, 0,
	78, 81, 92, 93, 97, 95, 91, 90, 0, 0,
	0, 0, 77, 0, 0, 0, 0, 84, 85, 87,
	88, 89, 86, 0, 0, 82, 83, 107, 104, 105,
	0, 0, 0, 0, 0, 0, 80, 0, 0, 0,
	0, 0, 248, 76, 94, 96, 98, 99, 100, 0,
	101, 102, 103, 106, 0, 0, 0, 79, 0, 0,
	75, 0, 0, 78, 81, 92, 93, 97, 95, 91,
	90, 0, 0, 0, 0, 77, 0, 0, 0, 0,
	84, 85, 87, 88, 89, 86, 0, 0, 82, 83,
	107, 104, 105, 0, 0, 0, 0, 0, 0, 80,
	0, 0, 0, 0, 0, 0, 76, 94, 96, 98,
	99, 100, 0, 101, 102, 103, 106, 0, 0, 0,
	79, 0, 233, 75, 0, 0, 78, 81, 92, 93,
	97, 95, 91, 90, 0, 0, 0, 0, 77, 0,
	0, 0, 0, 84, 85, 87, 88, 89, 86, 0,
	0, 82, 83, 107, 104, 105, 0, 0, 0, 0,
	0, 0, 80, 0, 0, 0, 0, 0, 223, 76,
	94, 96, 98, 99, 100, 0, 101, 102, 103, 106,
	0, 0, 0, 79, 0, 0, 75, 0, 0, 78,
	81, 92, 93, 97, 95, 91, 90, 0, 0, 0,
	0, 77, 0, 0, 0, 0, 84, 85, 87, 88,
	89, 86, 0, 0, 82, 83, 107, 104, 105, 0,
	0, 0, 0, 0, 0, 80, 0, 0, 0, 0,
	0, 0, 76, 94, 96, 98, 99, 100, 0, 101,
	102, 103, 106, 0, 0, 0, 79, 219, 0, 75,
	0, 0, 78, 81, 92, 93, 97, 95, 91, 90,
	0, 0, 0, 0, 77, 0, 0, 0, 0, 84,
	85, 87, 88, 89, 86, 0, 0, 82, 83, 107,
	104, 105, 0, 0, 0, 0, 0, 0, 80, 0,
	0, 0, 0, 0, 0, 76, 94, 96, 98, 99,
	100, 0, 101, 102, 103, 106, 0, 0, 0, 79,
	198, 0, 75, 0, 0, 78, 81, 92, 93, 97,
	95, 91, 90, 0, 0, 0, 0, 77, 0, 0,
	0, 0, 84, 85, 87, 88, 89, 86, 0, 0,
	82, 83, 107, 104, 105, 0, 0, 0, 0, 0,
	0, 80, 0, 0, 0, 0, 0, 0, 76, 94,
	96, 98, 99, 100, 0, 101, 102, 103, 106, 0,
	190, 0, 79, 0, 0, 75, 0, 0, 78, 81,
	92, 93, 97, 95, 91, 90, 0, 0, 0, 0,
	77, 0, 0, 0, 0, 84, 85, 87, 88, 89,
	86, 0, 0, 82, 83, 107, 104, 105, 0, 0,
	0, 0, 0, 0, 80, 0, 0, 0, 0, 0,
	0, 76, 94, 96, 98, 99, 100, 0, 101, 102,
	103, 106, 0, 181, 0, 79, 0, 0, 75, 0,
	0, 78, 81, 92, 93, 97, 95, 91, 90, 0,
	0, 0, 0, 77, 0, 0, 0, 0, 84, 85,
	87, 88, 89, 86, 0, 0, 82, 83, 107, 104,
	105, 0, 0, 0, 0, 0, 0, 80, 0, 0,
	0, 0, 74, 0, 76, 94, 96, 98, 99, 100,
	0, 101, 102, 103, 106, 0, 0, 0, 79, 0,
	0, 75, 0, 0, 78, 81, 92, 93, 97, 95,
	91, 90, 0, 0, 0, 0, 77, 0, 0, 0,
	0, 84, 85, 87, 88, 89, 86, 0, 0, 82,
	83, 107, 104, 105, 0, 0, 0, 0, 0, 0,
	80, 0, 0, 0, 0, 0, 0, 76, 94, 96,
	98, 99, 100, 0, 101, 102, 103, 106, 0, 0,
	0, 79, 0, 0, 75, 0, 0, 78, 81, 92,
	93, 97, 95, 91, 90, 0, 0, 0, 0, 77,
	0, 0, 0, 0, 84, 85, 87, 88, 89, 86,
	0, 0, 82, 83, 107, 104, 105, 0, 0, 0,
	0, 0, 0, 80, 0, 0, 0, 0, 0, 0,
	76, 94, 96, 98, 99, 100, 0, 101, 102, 103,
	106, 0, 0, 0, 79, 0, 0, 75, 0, 0,
	212, 81, 92, 93, 97, 95, 91, 90, 0, 0,
	0, 0, 77, 0, 0, 0, 0, 84, 85, 87,
	88, 89, 86, 0, 0, 82, 83, 107, 104, 105,
	0, 0, 0, 0, 0, 0, 80, 0, 0, 0,
	0, 0, 0, 76, 94, 96, 98, 99, 100, 0,
	101, 102, 103, 106, 0, 0, 0, 79, 0, 0,
	75, 0, 0, 211, 81, 92, 93, 97, 95, 91,
	90, 0, 0, 0, 0, 77, 0, 0, 0, 0,
	84, 85, 87, 88, 89, 86, 0, 0, 82, 83,
	107, 104, 105, 0, 0, 0, 0, 0, 0, 80,
	0, 0, 0, 0, 0, 0, 76, 94, 96, 98,
	99, 100, 0, 101, 102, 103, 106, 0, 0, 0,
	146, 0, 0, 75, 0, 0, 78, 34, 44, 45,
	0, 0, 30, 13, 42, 14, 25, 0, 26, 0,
	0, 0, 0, 0, 0, 0, 37, 46, 47, 48,
	0, 15, 18, 0, 0, 0, 0, 0, 0, 0,
	0, 11, 12, 0, 0, 0, 0, 0, 27, 0,
	0, 20, 0, 38, 39, 0, 36, 40, 21, 0,
	0, 0, 0, 0, 0, 52, 0, 54, 56, 0,
	0, 55, 0, 32, 0, 33, 0, 0, 31, 0,
	0, 0, 53, 81, 92, 93, 97, 95, 91, 90,
	0, 0, 0, 0, 77, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 82, 83, 107,
	104, 105, 0, 0, 0, 0, 0, 0, 80, 0,
	0, 0, 0, 0, 0, 76, 94, 96, 98, 99,
	100, 0, 101, 102, 103, 106, 0, 0, 0, 79,
	0, 0, 75, 0, 0, 78, 81, 92, 93, 97,
	95, 0, 90, 0, 0, 0, 0, 114, 44, 45,
	0, 0, 30, 0, 42, 0, 0, 0, 0, 0,
	82, 83, 107, 104, 105, 0, 37, 46, 47, 48,
	0, 80, 0, 0, 0, 0, 0, 0, 0, 94,
	96, 98, 99, 100, 0, 101, 102, 103, 106, 0,
	0, 0, 79, 38, 39, 75, 36, 40, 78, 81,
	92, 93, 97, 95, 0, 52, 0, 54, 56, 0,
	0, 55, 0, 109, 0, 33, 0, 112, 31, 0,
	0, 0, 53, 82, 83, 107, 104, 105, 0, 0,
	0, 0, 0, 0, 80, 0, 0, 0, 0, 0,
	0, 0, 94, 96, 98, 99, 100, 0, 101, 102,
	103, 106, 34, 44, 45, 79, 0, 30, 75, 0,
	0, 78, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 37, 46, 47, 48, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 34, 44, 45, 0, 0, 30,
	0, 0, 0, 0, 0, 0, 0, 0, 38, 39,
	0, 36, 40, 37, 46, 47, 48, 0, 0, 0,
	52, 0, 54, 56, 0, 0, 55, 0, 32, 0,
	33, 0, 0, 31, 296, 0, 0, 53, 0, 0,
	38, 39, 0, 36, 40, 0, 0, 0, 0, 0,
	0, 0, 52, 0, 54, 56, 0, 0, 55, 0,
	32, 0, 33, 0, 0, 31, 275, 0, 0, 53,
	34, 44, 45, 0, 0, 30, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 37,
	46, 47, 48, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 34, 44, 45, 0, 0, 30, 0, 0,
	0, 0, 0, 0, 0, 0, 38, 39, 0, 36,
	40, 37, 46, 47, 48, 0, 0, 0, 52, 0,
	54, 56, 0, 0, 55, 0, 32, 0, 33, 0,
	234, 31, 0, 0, 0, 53, 0, 0, 38, 39,
	0, 36, 40, 0, 0, 192, 0, 0, 0, 0,
	52, 0, 54, 56, 0, 0, 55, 0, 32, 0,
	33, 0, 0, 31, 34, 44, 45, 53, 0, 30,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 37, 46, 47, 48, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 34, 44, 45, 0,
	0, 30, 0, 0, 0, 0, 0, 0, 0, 0,
	38, 39, 0, 36, 40, 37, 46, 47, 48, 0,
	0, 0, 52, 0, 54, 56, 0, 0, 55, 0,
	32, 0, 33, 0, 187, 31, 0, 0, 0, 53,
	0, 0, 38, 39, 0, 36, 40, 0, 0, 150,
	0, 0, 0, 0, 52, 0, 54, 56, 0, 0,
	55, 0, 32, 0, 33, 0, 0, 31, 34, 44,
	45, 53, 0, 30, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 37, 46, 47,
	48, 34, 44, 45, 0, 0, 30, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	37, 46, 47, 48, 38, 39, 0, 36, 40, 0,
	0, 0, 0, 0, 0, 0, 52, 0, 54, 56,
	0, 0, 55, 0, 32, 0, 33, 38, 39, 31,
	36, 40, 0, 53, 0, 0, 0, 0, 0, 52,
	0, 54, 56, 0, 0, 55, 0, 329, 0, 33,
	0, 0, 31, 34, 44, 45, 53, 0, 30, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 37, 46, 47, 48, 34, 44, 45, 0,
	0, 30, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 37, 46, 47, 48, 38,
	39, 0, 36, 40, 0, 0, 0, 0, 0, 0,
	0, 52, 0, 54, 56, 0, 0, 55, 0, 287,
	0, 33, 38, 39, 31, 36, 40, 0, 53, 0,
	0, 0, 0, 0, 52, 0, 54, 56, 0, 0,
	55, 0, 285, 0, 33, 0, 0, 31, 34, 44,
	45, 53, 0, 30, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 37, 46, 47,
	48, 71, 44, 45, 0, 0, 30, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	37, 46, 47, 48, 38, 39, 0, 36, 40, 0,
	0, 0, 0, 0, 0, 0, 52, 0, 54, 56,
	0, 0, 55, 0, 231, 0, 33, 38, 39, 31,
	36, 40, 0, 53, 81, 0, 0, 0, 0, 52,
	0, 54, 56, 0, 0, 55, 0, 32, 0, 33,
	0, 0, 31, 0, 0, 0, 53, 0, 82, 83,
	107, 104, 105, 0, 0, 0, 0, 0, 0, 80,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 98,
	99, 100, 0, 101, 102, 103, 106, 0, 0, 0,
	79, 0, 0, 75, 0, 0, 78,
}
var yyPact = [...]int{

	-55, -1000, 2583, -55, -1000, -72, -72, -1000, -1000, -1000,
	-1000, -1000, -1000, 3154, 3154, 267, 236, -1000, 162, -1000,
	3367, 86, 2256, -1000, -1000, 3154, 2733, 3154, -28, -1000,
	136, -72, -72, 3154, 70, -1000, 84, 81, 80, 3154,
	74, -1000, 265, -44, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 3154, 3154, 3154, 3154, 3154, -1000, -1000, -1000,
	-1000, -1000, 2583, -72, -1000, -40, 2319, 2319, 161, 166,
	-55, 73, 2508, 3154, 3154, 3082, 3154, 3154, 266, 3154,
	3154, 3154, -1000, -1000, 3154, 3154, 3154, 3154, 3154, 3154,
	3154, 3154, 3154, 3154, 3154, 3154, 3154, 3154, 3154, 3154,
	3154, 3154, 3154, 3154, 3154, 3154, 3154, 3154, 2193, -55,
	64, 618, 3050, -16, 70, 2130, 2978, 265, 67, 3154,
	-72, 3154, 2067, 3154, 3154, 260, 72, 2319, 3154, -46,
	-1000, 3154, -72, -6, -6, -6, -28, 2445, -28, 2382,
	-1000, -55, 3154, -55, 143, 3154, 3154, 2004, 2319, 555,
	3154, 1941, 2647, -1000, 152, 2319, -5, 2319, 2319, 2319,
	2319, 2319, 2319, 2773, 2710, 3408, 3408, 3408, 3408, 3408,
	3408, 200, 200, 200, -5, -5, -5, -5, -5, -5,
	-5, -55, 135, -72, 3154, -72, -55, 3344, 1878, 2946,
	-72, 492, 3154, 124, 265, -39, -57, 1815, -1000, 101,
	1752, -49, -1000, 260, 108, 258, -14, 429, 3154, -40,
	3154, 255, 253, 134, 1689, 128, 216, 71, 60, -1000,
	2870, -1000, 1626, 3154, 65, -1000, 127, -1000, 1563, 252,
	125, -55, 1500, 3272, 3249, 1437, 208, 2838, -1000, 1374,
	160, 63, 57, -72, -26, -72, -72, 123, 3154, 62,
	-1000, -1000, 248, -1000, 41, -33, 38, -35, -1000, -1000,
	3154, -40, 2319, -28, -1000, -1000, -1000, -55, -1000, 188,
	58, -1000, 47, -1000, 1311, -1000, -1000, 2647, -1000, -1000,
	-55, -1000, -1000, 118, -55, -55, 1248, -55, 1185, 3177,
	-29, -1000, -1000, 176, 3154, 1122, -1000, -1000, -55, 158,
	157, 10, -72, -1000, 3154, -1000, 2319, -1000, -1000, -1000,
	3154, -1000, -1000, 3154, 3154, 1059, 116, 156, -55, -1000,
	-1000, -1000, 115, -1000, 113, 111, -55, 110, -55, -55,
	996, 109, -1000, -1000, -55, 933, -18, -1000, 104, -55,
	-55, 150, 870, 807, 366, 744, -1000, -1000, -55, 102,
	-1000, -1000, -1000, 100, -1000, 99, 98, -55, -1000, -1000,
	-55, -55, -1000, 97, 96, -55, 3154, -1000, -1000, 3154,
	-1000, 95, 206, -1000, -1000, -1000, 93, -1000, -1000, -1000,
	-1000, 92, 2319, 681, 141, 149, -1000, -1000, -1000, 147,
	-55, -55, 90, 88, -1000, -1000,
}
var yyPgo = [...]int{

	0, 13, 319, 222, 247, 318, 317, 316, 313, 309,
	308, 2, 1, 30, 0, 306, 9, 303, 5, 300,
	297, 4, 296, 291, 289, 288, 287, 286, 283, 282,
	280, 273, 32, 6, 16, 7,
}
var yyR1 = [...]int{

	0, 1, 1, 2, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 4, 4, 5, 6, 6,
	7, 7, 7, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 9, 10, 10, 10, 10, 10,
	11, 11, 12, 19, 19, 19, 15, 15, 15, 16,
	16, 16, 18, 18, 20, 20, 20, 20, 20, 20,
	13, 13, 13, 13, 14, 14, 14, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 14, 21, 17, 17,
	17, 17, 17, 22, 22, 22, 23, 23, 23, 23,
	23, 23, 23, 24, 24, 24, 24, 25, 25, 25,
	25, 25, 25, 25, 25, 26, 26, 27, 27, 27,
	27, 27, 27, 28, 28, 28, 29, 29, 29, 29,
	29, 29, 29, 30, 30, 31, 31, 31, 32, 32,
	34, 34, 35, 33, 33, 33, 33,
}
var yyR2 = [...]int{

	0, 1, 2, 2, 3, 0, 1, 1, 1, 2,
	2, 5, 1, 1, 13, 12, 9, 8, 1, 6,
	5, 6, 5, 4, 1, 1, 1, 4, 3, 3,
	5, 7, 5, 4, 7, 5, 6, 7, 7, 8,
	7, 8, 8, 9, 7, 0, 1, 1, 2, 2,
	4, 4, 3, 0, 2, 3, 0, 3, 6, 0,
	1, 4, 1, 3, 6, 5, 5, 6, 5, 5,
	0, 1, 4, 4, 1, 1, 5, 3, 3, 7,
	8, 8, 9, 5, 5, 3, 5, 4, 5, 4,
	4, 4, 1, 4, 4, 5, 7, 5, 7, 9,
	7, 3, 2, 4, 6, 3, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
	4, 2, 4, 1, 1, 1, 1, 2, 2, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 0, 1, 2, 1, 1, 0, 1,
	1, 2, 1, 0, 2, 1, 1,
}
var yyChk = [...]int{

	-1000, -1, -30, -2, -31, 74, -34, -35, 80, -3,
	-4, 38, 39, 10, 12, 28, -7, -8, 29, -9,
	48, 55, -14, -5, -6, 13, 15, 45, -21, -17,
	9, 75, 70, 72, 4, -20, 53, 23, 50, 51,
	54, -22, 11, -13, 5, 6, 24, 25, 26, -23,
	-24, -25, 62, 79, 64, 68, 65, -29, -28, -27,
	-26, -30, -31, -34, -35, -13, -14, -14, 4, 14,
	70, 4, -14, 72, 56, 75, 58, 27, 78, 72,
	51, 16, 40, 41, 32, 33, 37, 34, 35, 36,
	22, 21, 17, 18, 59, 20, 60, 19, 61, 62,
	63, 65, 66, 67, 43, 44, 68, 42, -14, 70,
	-16, -14, 74, -4, 4, -14, 75, 72, 4, -32,
	-34, -32, -14, 72, 72, 72, 72, -14, 72, -16,
	4, 56, 77, -14, -14, -14, -21, -14, -21, -14,
	-3, 70, 13, 70, -1, 72, 72, -14, -14, -14,
	57, -14, -14, 4, -13, -14, -14, -14, -14, -14,
	-14, -14, -14, -14, -14, -14, -14, -14, -14, -14,
	-14, -14, -14, -14, -14, -14, -14, -14, -14, -14,
	-14, 70, -1, -34, 16, 77, 70, 74, -14, 74,
	70, -14, 57, -16, 72, -13, -15, -14, 73, -13,
	-14, -18, 4, 49, -19, 52, 75, -14, 56, -13,
	-32, 78, 78, -1, -14, -1, 71, -13, -13, 73,
	57, 76, -14, 57, 8, 73, -1, 71, -14, -32,
	-1, 70, -14, 74, 74, -14, -32, 57, 76, -14,
	73, 8, -16, 77, -33, -34, 77, -33, 57, 8,
	73, 73, 78, 73, -18, 75, -18, 4, 76, 73,
	77, -13, -14, -21, 4, 4, 71, 70, 71, 30,
	8, 73, 8, 73, -14, 76, 76, -14, 73, 71,
	70, 4, 71, -1, 70, 70, -14, 70, -14, 74,
	-10, -12, -11, 47, 46, -14, 76, 76, 70, 73,
	73, 8, -34, 76, -32, 71, -14, 73, 4, 73,
	77, 76, 73, 77, 77, -14, -1, 4, 70, 73,
	73, 76, -1, 71, -1, -1, 70, -1, 70, 70,
	-14, -32, -11, -12, 57, -14, -13, 76, -1, 70,
	70, 73, -14, -14, -14, -14, 73, 71, 70, -1,
	71, 71, 71, -1, 71, -1, -1, 70, 71, -1,
	57, 57, 71, -1, -1, 70, 57, 73, 73, 77,
	73, -1, 71, 71, 71, 71, -1, -1, -1, 71,
	71, -1, -14, -14, 71, 31, 71, 71, 73, 31,
	70, 70, -1, -1, 71, 71,
}
var yyDef = [...]int{

	153, -2, -2, 153, 154, 157, 156, 160, 162, 3,
	6, 7, 8, 70, 0, 0, 12, 13, 0, 18,
	0, 0, -2, 25, 26, 0, -2, 0, 74, 75,
	0, 158, 158, 0, 107, 92, 0, 0, 0, 0,
	0, 106, 59, 0, 108, 109, 110, 111, 112, 113,
	114, 115, 0, 0, 0, 0, 0, 123, 124, 125,
	126, 2, -2, 155, 161, 9, 71, 10, 0, 0,
	153, 107, 0, 0, 0, 0, 0, 0, 0, 70,
	0, 0, 127, 128, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 153,
	0, 71, 0, 0, -2, 0, 0, 59, 0, 70,
	159, 56, 0, 70, 0, 0, 53, 102, 0, 0,
	60, 70, 158, 116, 117, 118, -2, 0, -2, 0,
	4, 153, 0, 153, 0, 70, 70, 0, 28, 0,
	0, 0, 77, 78, 0, 101, 105, 129, 130, 131,
	132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
	142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
	152, 153, 0, 156, 0, 158, 153, 0, 0, 0,
	158, 0, 0, 0, 59, 163, 163, 0, 85, 0,
	0, 0, 62, 0, 0, 0, 0, 0, 70, 29,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 23,
	0, 91, 0, 0, 0, 89, 0, 33, 0, 0,
	0, 153, 0, 0, 0, 0, 45, 0, 90, 0,
	0, 0, 0, -2, 0, 165, -2, 0, 0, 0,
	87, 93, 0, 94, 0, 0, 0, 0, 54, 103,
	0, 27, 72, -2, -2, -2, 11, 153, 32, 0,
	0, -2, 0, -2, 0, 68, 69, 76, 88, 30,
	153, 61, 35, 0, 153, 153, 0, 153, 0, 0,
	158, 46, 47, 0, 70, 0, 65, 66, 153, 0,
	0, 0, -2, 83, 0, 84, 57, 86, 63, 95,
	0, 55, 97, 0, 0, 0, 0, 0, 153, -2,
	-2, 67, 0, 36, 0, 0, 153, 0, 153, 153,
	0, 0, 48, 49, 153, 71, 0, 64, 0, 153,
	153, 0, 0, 0, 0, 0, 104, 31, 153, 0,
	34, 37, 38, 0, 40, 0, 0, 153, 44, 52,
	153, 153, 79, 0, 0, 153, 0, 96, 98, 0,
	100, 0, 17, 39, 41, 42, 0, 50, 51, 80,
	81, 0, 58, 0, 16, 0, 43, 82, 99, 0,
	153, 153, 0, 0, 15, 14,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	80, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 79, 3, 3, 3, 67, 68, 3,
	72, 73, 65, 61, 77, 62, 78, 66, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 57, 74,
	59, 56, 60, 58, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 75, 3, 76, 64, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 70, 63, 71,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 69,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:96
		{
			yyVAL.compstmt = nil
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:100
		{
			yyVAL.compstmt = yyDollar[1].stmts
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:106
		{
			if yyDollar[2].stmt != nil {
				yyVAL.stmts = &ast.StmtsStmt{Stmts: []ast.Stmt{yyDollar[2].stmt}}
			}
			if l, ok := yylex.(*Lexer); ok {
				l.stmt = yyVAL.stmts
			}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:115
		{
			if yyDollar[3].stmt != nil {
				if yyDollar[1].stmts == nil {
					yyVAL.stmts = &ast.StmtsStmt{Stmts: []ast.Stmt{yyDollar[3].stmt}}
				} else {
					stmts := yyDollar[1].stmts.(*ast.StmtsStmt)
					stmts.Stmts = append(stmts.Stmts, yyDollar[3].stmt)
				}
				if l, ok := yylex.(*Lexer); ok {
					l.stmt = yyVAL.stmts
				}
			}
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:131
		{
			yyVAL.stmt = nil
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:135
		{
			yyVAL.stmt = yyDollar[1].stmt_var_or_lets
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:139
		{
			yyVAL.stmt = &ast.BreakStmt{}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:144
		{
			yyVAL.stmt = &ast.ContinueStmt{}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:149
		{
			yyVAL.stmt = &ast.ReturnStmt{Exprs: yyDollar[2].exprs}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:154
		{
			yyVAL.stmt = &ast.ThrowStmt{Expr: yyDollar[2].expr}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:159
		{
			yyVAL.stmt = &ast.ModuleStmt{Name: yyDollar[2].tok.Lit, Stmt: yyDollar[4].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:164
		{
			yyVAL.stmt = yyDollar[1].stmt_if
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:168
		{
			yyVAL.stmt = yyDollar[1].stmt_for
		}
	case 14:
		yyDollar = yyS[yypt-13 : yypt+1]
//line parser.go.y:172
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Var: yyDollar[6].tok.Lit, Catch: yyDollar[8].compstmt, Finally: yyDollar[12].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 15:
		yyDollar = yyS[yypt-12 : yypt+1]
//line parser.go.y:177
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Catch: yyDollar[7].compstmt, Finally: yyDollar[11].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 16:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:182
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Var: yyDollar[6].tok.Lit, Catch: yyDollar[8].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 17:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:187
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Catch: yyDollar[7].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:192
		{
			yyVAL.stmt = yyDollar[1].stmt_switch
		}
	case 19:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:196
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.CallExpr{Name: yyDollar[2].tok.Lit, SubExprs: yyDollar[4].exprs, VarArg: true, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[2].tok.Position())
		}
	case 20:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:201
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.CallExpr{Name: yyDollar[2].tok.Lit, SubExprs: yyDollar[4].exprs, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[2].tok.Position())
		}
	case 21:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:206
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.AnonCallExpr{Expr: yyDollar[2].expr, SubExprs: yyDollar[4].exprs, VarArg: true, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[2].expr.Position())
		}
	case 22:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:211
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.AnonCallExpr{Expr: yyDollar[2].expr, SubExprs: yyDollar[4].exprs, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:216
		{
			yyVAL.stmt = &ast.CloseStmt{Expr: yyDollar[3].expr}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:221
		{
			yyVAL.stmt = &ast.ExprStmt{Expr: yyDollar[1].expr}
			yyVAL.stmt.SetPosition(yyDollar[1].expr.Position())
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:228
		{
			yyVAL.stmt_var_or_lets = yyDollar[1].stmt_var
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:232
		{
			yyVAL.stmt_var_or_lets = yyDollar[1].stmt_lets
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:238
		{
			yyVAL.stmt_var = &ast.VarStmt{Names: yyDollar[2].expr_idents, Exprs: yyDollar[4].exprs}
			yyVAL.stmt_var.SetPosition(yyDollar[1].tok.Position())
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:245
		{
			yyVAL.stmt_lets = &ast.LetsStmt{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{yyDollar[3].expr}}
			yyVAL.stmt_lets.SetPosition(yyDollar[1].expr.Position())
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:250
		{
			if len(yyDollar[1].exprs) == 2 && len(yyDollar[3].exprs) == 1 {
				if _, ok := yyDollar[3].exprs[0].(*ast.ItemExpr); ok {
					yyVAL.stmt_lets = &ast.LetMapItemStmt{LHSS: yyDollar[1].exprs, RHS: yyDollar[3].exprs[0]}
				} else {
					yyVAL.stmt_lets = &ast.LetsStmt{LHSS: yyDollar[1].exprs, RHSS: yyDollar[3].exprs}
				}
			} else {
				yyVAL.stmt_lets = &ast.LetsStmt{LHSS: yyDollar[1].exprs, RHSS: yyDollar[3].exprs}
			}
		}
	case 30:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:264
		{
			yyVAL.stmt_if = &ast.IfStmt{If: yyDollar[2].expr, Then: yyDollar[4].compstmt, Else: nil}
			yyVAL.stmt_if.SetPosition(yyDollar[1].tok.Position())
		}
	case 31:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:269
		{
			ifStmt := yyDollar[1].stmt_if.(*ast.IfStmt)
			ifStmt.ElseIf = append(ifStmt.ElseIf, &ast.IfStmt{If: yyDollar[4].expr, Then: yyDollar[6].compstmt})
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:274
		{
			ifStmt := yyDollar[1].stmt_if.(*ast.IfStmt)
			if ifStmt.Else != nil {
				yylex.Error("multiple else statement")
			}
			ifStmt.Else = yyDollar[4].compstmt
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:284
		{
			yyVAL.stmt_for = &ast.LoopStmt{Stmt: yyDollar[3].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 34:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:289
		{
			if len(yyDollar[2].expr_idents) < 1 {
				yylex.Error("missing identifier")
			} else if len(yyDollar[2].expr_idents) > 2 {
				yylex.Error("too many identifiers")
			} else {
				yyVAL.stmt_for = &ast.ForStmt{Vars: yyDollar[2].expr_idents, Value: yyDollar[4].expr, Stmt: yyDollar[6].compstmt}
				yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
			}
		}
	case 35:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:300
		{
			yyVAL.stmt_for = &ast.LoopStmt{Expr: yyDollar[2].expr, Stmt: yyDollar[4].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 36:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:305
		{
			yyVAL.stmt_for = &ast.CForStmt{Stmt: yyDollar[5].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 37:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:310
		{
			yyVAL.stmt_for = &ast.CForStmt{Expr3: yyDollar[4].expr, Stmt: yyDollar[6].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 38:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:315
		{
			yyVAL.stmt_for = &ast.CForStmt{Expr2: yyDollar[3].expr, Stmt: yyDollar[6].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 39:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:320
		{
			yyVAL.stmt_for = &ast.CForStmt{Expr2: yyDollar[3].expr, Expr3: yyDollar[5].expr, Stmt: yyDollar[7].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 40:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:325
		{
			yyVAL.stmt_for = &ast.CForStmt{Stmt1: yyDollar[2].stmt_var_or_lets, Stmt: yyDollar[6].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 41:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:330
		{
			yyVAL.stmt_for = &ast.CForStmt{Stmt1: yyDollar[2].stmt_var_or_lets, Expr3: yyDollar[5].expr, Stmt: yyDollar[7].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 42:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:335
		{
			yyVAL.stmt_for = &ast.CForStmt{Stmt1: yyDollar[2].stmt_var_or_lets, Expr2: yyDollar[4].expr, Stmt: yyDollar[7].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 43:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:340
		{
			yyVAL.stmt_for = &ast.CForStmt{Stmt1: yyDollar[2].stmt_var_or_lets, Expr2: yyDollar[4].expr, Expr3: yyDollar[6].expr, Stmt: yyDollar[8].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 44:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:347
		{
			switchStmt := yyDollar[5].stmt_switch_cases.(*ast.SwitchStmt)
			switchStmt.Expr = yyDollar[2].expr
			yyVAL.stmt_switch = switchStmt
			yyVAL.stmt_switch.SetPosition(yyDollar[1].tok.Position())
		}
	case 45:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:356
		{
			yyVAL.stmt_switch_cases = &ast.SwitchStmt{}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:360
		{
			yyVAL.stmt_switch_cases = &ast.SwitchStmt{Default: yyDollar[1].stmt_switch_default}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:364
		{
			yyVAL.stmt_switch_cases = &ast.SwitchStmt{Cases: []ast.Stmt{yyDollar[1].stmt_switch_case}}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:368
		{
			switchStmt := yyDollar[1].stmt_switch_cases.(*ast.SwitchStmt)
			switchStmt.Cases = append(switchStmt.Cases, yyDollar[2].stmt_switch_case)
			yyVAL.stmt_switch_cases = switchStmt
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:374
		{
			switchStmt := yyDollar[1].stmt_switch_cases.(*ast.SwitchStmt)
			if switchStmt.Default != nil {
				yylex.Error("multiple default statement")
			}
			switchStmt.Default = yyDollar[2].stmt_switch_default
			yyVAL.stmt_switch_cases = switchStmt
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:385
		{
			yyVAL.stmt_switch_case = &ast.SwitchCaseStmt{Exprs: []ast.Expr{yyDollar[2].expr}, Stmt: yyDollar[4].compstmt}
			yyVAL.stmt_switch_case.SetPosition(yyDollar[1].tok.Position())
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:390
		{
			yyVAL.stmt_switch_case = &ast.SwitchCaseStmt{Exprs: yyDollar[2].exprs, Stmt: yyDollar[4].compstmt}
			yyVAL.stmt_switch_case.SetPosition(yyDollar[1].tok.Position())
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:397
		{
			yyVAL.stmt_switch_default = yyDollar[3].compstmt
		}
	case 53:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:402
		{
			yyVAL.array_count = ast.ArrayCount{Count: 0}
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:406
		{
			yyVAL.array_count = ast.ArrayCount{Count: 1}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:410
		{
			yyVAL.array_count.Count = yyVAL.array_count.Count + 1
		}
	case 56:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:415
		{
			yyVAL.map_expr = make(map[ast.Expr]ast.Expr)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:419
		{
			mapExpr := make(map[ast.Expr]ast.Expr)
			mapExpr[yyDollar[1].expr] = yyDollar[3].expr
			yyVAL.map_expr = mapExpr
		}
	case 58:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:425
		{
			if len(yyDollar[1].map_expr) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyDollar[1].map_expr[yyDollar[4].expr] = yyDollar[6].expr
		}
	case 59:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:433
		{
			yyVAL.expr_idents = []string{}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:437
		{
			yyVAL.expr_idents = []string{yyDollar[1].tok.Lit}
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:441
		{
			if len(yyDollar[1].expr_idents) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyVAL.expr_idents = append(yyDollar[1].expr_idents, yyDollar[4].tok.Lit)
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:450
		{
			yyVAL.expr_type = yyDollar[1].tok.Lit
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:454
		{
			yyVAL.expr_type = yyVAL.expr_type + "." + yyDollar[3].tok.Lit
		}
	case 64:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:460
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr_ident, Begin: yyDollar[3].expr, End: yyDollar[5].expr}
		}
	case 65:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:464
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr_ident, Begin: yyDollar[3].expr, End: nil}
		}
	case 66:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:468
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr_ident, Begin: nil, End: yyDollar[4].expr}
		}
	case 67:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:472
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr, Begin: yyDollar[3].expr, End: yyDollar[5].expr}
		}
	case 68:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:476
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr, Begin: yyDollar[3].expr, End: nil}
		}
	case 69:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:480
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr, Begin: nil, End: yyDollar[4].expr}
		}
	case 70:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:486
		{
			yyVAL.exprs = nil
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:490
		{
			yyVAL.exprs = []ast.Expr{yyDollar[1].expr}
		}
	case 72:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:494
		{
			if len(yyDollar[1].exprs) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[4].expr)
		}
	case 73:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:501
		{
			if len(yyDollar[1].exprs) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[4].expr_ident)
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:510
		{
			yyVAL.expr = yyDollar[1].expr_ident
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:514
		{
			yyVAL.expr = yyDollar[1].expr_literals
		}
	case 76:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:518
		{
			yyVAL.expr = &ast.TernaryOpExpr{Expr: yyDollar[1].expr, LHS: yyDollar[3].expr, RHS: yyDollar[5].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:523
		{
			yyVAL.expr = &ast.NilCoalescingOpExpr{LHS: yyDollar[1].expr, RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:528
		{
			yyVAL.expr = &ast.MemberExpr{Expr: yyDollar[1].expr, Name: yyDollar[3].tok.Lit}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 79:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:533
		{
			yyVAL.expr = &ast.FuncExpr{Params: yyDollar[3].expr_idents, Stmt: yyDollar[6].compstmt}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 80:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:538
		{
			yyVAL.expr = &ast.FuncExpr{Params: yyDollar[3].expr_idents, Stmt: yyDollar[7].compstmt, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 81:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:543
		{
			yyVAL.expr = &ast.FuncExpr{Name: yyDollar[2].tok.Lit, Params: yyDollar[4].expr_idents, Stmt: yyDollar[7].compstmt}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 82:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:548
		{
			yyVAL.expr = &ast.FuncExpr{Name: yyDollar[2].tok.Lit, Params: yyDollar[4].expr_idents, Stmt: yyDollar[8].compstmt, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 83:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:553
		{
			yyVAL.expr = &ast.ArrayExpr{Exprs: yyDollar[3].exprs}
			if l, ok := yylex.(*Lexer); ok {
				yyVAL.expr.SetPosition(l.pos)
			}
		}
	case 84:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:558
		{
			yyVAL.expr = &ast.MapExpr{MapExpr: yyDollar[3].map_expr}
			if l, ok := yylex.(*Lexer); ok {
				yyVAL.expr.SetPosition(l.pos)
			}
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:563
		{
			yyVAL.expr = &ast.ParenExpr{SubExpr: yyDollar[2].expr}
			if l, ok := yylex.(*Lexer); ok {
				yyVAL.expr.SetPosition(l.pos)
			}
		}
	case 86:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:568
		{
			yyVAL.expr = &ast.CallExpr{Name: yyDollar[1].tok.Lit, SubExprs: yyDollar[3].exprs, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 87:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:573
		{
			yyVAL.expr = &ast.CallExpr{Name: yyDollar[1].tok.Lit, SubExprs: yyDollar[3].exprs}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 88:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:578
		{
			yyVAL.expr = &ast.AnonCallExpr{Expr: yyDollar[1].expr, SubExprs: yyDollar[3].exprs, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 89:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:583
		{
			yyVAL.expr = &ast.AnonCallExpr{Expr: yyDollar[1].expr, SubExprs: yyDollar[3].exprs}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 90:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:588
		{
			yyVAL.expr = &ast.ItemExpr{Item: yyDollar[1].expr_ident, Index: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr_ident.Position())
		}
	case 91:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:593
		{
			yyVAL.expr = &ast.ItemExpr{Item: yyDollar[1].expr, Index: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:598
		{
			yyVAL.expr = yyDollar[1].expr_slice
			yyVAL.expr.SetPosition(yyDollar[1].expr_slice.Position())
		}
	case 93:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:603
		{
			yyVAL.expr = &ast.LenExpr{Expr: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 94:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:608
		{
			yyVAL.expr = &ast.NewExpr{Type: yyDollar[3].expr_type}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 95:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:613
		{
			yyVAL.expr = &ast.MakeChanExpr{Type: yyDollar[4].expr_type, SizeExpr: nil}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 96:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:618
		{
			yyVAL.expr = &ast.MakeChanExpr{Type: yyDollar[4].expr_type, SizeExpr: yyDollar[6].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 97:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:623
		{
			yyVAL.expr = &ast.MakeExpr{Dimensions: yyDollar[3].array_count.Count, Type: yyDollar[4].expr_type}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 98:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:628
		{
			yyVAL.expr = &ast.MakeExpr{Dimensions: yyDollar[3].array_count.Count, Type: yyDollar[4].expr_type, LenExpr: yyDollar[6].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 99:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:633
		{
			yyVAL.expr = &ast.MakeExpr{Dimensions: yyDollar[3].array_count.Count, Type: yyDollar[4].expr_type, LenExpr: yyDollar[6].expr, CapExpr: yyDollar[8].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 100:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:638
		{
			yyVAL.expr = &ast.MakeTypeExpr{Name: yyDollar[4].tok.Lit, Type: yyDollar[6].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:643
		{
			yyVAL.expr = &ast.ChanExpr{LHS: yyDollar[1].expr, RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:648
		{
			yyVAL.expr = &ast.ChanExpr{RHS: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 103:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:653
		{
			yyVAL.expr = &ast.DeleteExpr{WhatExpr: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 104:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:658
		{
			yyVAL.expr = &ast.DeleteExpr{WhatExpr: yyDollar[3].expr, KeyExpr: yyDollar[5].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:663
		{
			yyVAL.expr = &ast.IncludeExpr{ItemExpr: yyDollar[1].expr, ListExpr: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:671
		{
			yyVAL.expr_ident = &ast.IdentExpr{Lit: yyDollar[1].tok.Lit}
			yyVAL.expr_ident.SetPosition(yyDollar[1].tok.Position())
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:678
		{
			num, err := toNumber(yyDollar[1].tok.Lit)
			if err != nil {
				yylex.Error("invalid number: " + yyDollar[1].tok.Lit)
			}
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: num}
			yyVAL.expr_literals.SetPosition(yyDollar[1].tok.Position())
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:687
		{
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: stringToValue(yyDollar[1].tok.Lit)}
			yyVAL.expr_literals.SetPosition(yyDollar[1].tok.Position())
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:692
		{
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: trueValue}
			yyVAL.expr_literals.SetPosition(yyDollar[1].tok.Position())
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:697
		{
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: falseValue}
			yyVAL.expr_literals.SetPosition(yyDollar[1].tok.Position())
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:702
		{
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: nilValue}
			yyVAL.expr_literals.SetPosition(yyDollar[1].tok.Position())
		}
	case 116:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:714
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "-", Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 117:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:719
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "!", Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 118:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:724
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "^", Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 119:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:729
		{
			yyVAL.expr = &ast.AddrExpr{Expr: yyDollar[2].expr_ident}
			yyVAL.expr.SetPosition(yyDollar[2].expr_ident.Position())
		}
	case 120:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:734
		{
			yyVAL.expr = &ast.AddrExpr{Expr: &ast.MemberExpr{Expr: yyDollar[2].expr, Name: yyDollar[4].tok.Lit}}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 121:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:739
		{
			yyVAL.expr = &ast.DerefExpr{Expr: yyDollar[2].expr_ident}
			yyVAL.expr.SetPosition(yyDollar[2].expr_ident.Position())
		}
	case 122:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:744
		{
			yyVAL.expr = &ast.DerefExpr{Expr: &ast.MemberExpr{Expr: yyDollar[2].expr, Name: yyDollar[4].tok.Lit}}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:751
		{
			yyVAL.expr = &ast.OpExpr{Op: yyDollar[1].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:756
		{
			yyVAL.expr = &ast.OpExpr{Op: yyDollar[1].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:761
		{
			yyVAL.expr = &ast.OpExpr{Op: yyDollar[1].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:766
		{
			yyVAL.expr = &ast.OpExpr{Op: yyDollar[1].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 127:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:773
		{
			rhs := &ast.OpExpr{Op: &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "+", RHS: oneLiteral}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:781
		{
			rhs := &ast.OpExpr{Op: &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "-", RHS: oneLiteral}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:789
		{
			rhs := &ast.OpExpr{Op: &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "+", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 130:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:797
		{
			rhs := &ast.OpExpr{Op: &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "-", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:805
		{
			rhs := &ast.OpExpr{Op: &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "|", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 132:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:813
		{
			rhs := &ast.OpExpr{Op: &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "*", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 133:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:821
		{
			rhs := &ast.OpExpr{Op: &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "/", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:829
		{
			rhs := &ast.OpExpr{Op: &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "&", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 135:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:839
		{
			yyVAL.expr = &ast.BinaryOperator{LHS: yyDollar[1].expr, Operator: "&&", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 136:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:844
		{
			yyVAL.expr = &ast.BinaryOperator{LHS: yyDollar[1].expr, Operator: "||", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 137:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:851
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: "==", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:856
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: "!=", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:861
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: "<", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:866
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: "<=", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:871
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: ">", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:876
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: ">=", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:883
		{
			yyVAL.expr = &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "+", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 144:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:888
		{
			yyVAL.expr = &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "-", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:893
		{
			yyVAL.expr = &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "|", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:900
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "*", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:905
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "/", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:910
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "%", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:915
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "<<", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:920
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: ">>", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:925
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "&", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:930
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "**", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	}
	goto yystack /* stack new state and value */
}
