// +build !appengine

package packages

import (
	"net"
)

func init() {
	Packages["net"] = map[string]interface{}{
		"CIDRMask":                   net.CIDRMask,
		"Dial":                       net.Dial,
		"DialIP":                     net.DialIP,
		"DialTCP":                    net.DialTCP,
		"DialTimeout":                net.DialTimeout,
		"DialUDP":                    net.DialUDP,
		"DialUnix":                   net.DialUnix,
		"ErrWriteToConnected":        net.ErrWriteToConnected,
		"FileConn":                   net.FileConn,
		"FileListener":               net.FileListener,
		"FilePacketConn":             net.FilePacketConn,
		"FlagBroadcast":              net.FlagBroadcast,
		"FlagLoopback":               net.FlagLoopback,
		"FlagMulticast":              net.FlagMulticast,
		"FlagPointToPoint":           net.FlagPointToPoint,
		"FlagUp":                     net.FlagUp,
		"IPv4":                       net.IPv4,
		"IPv4Mask":                   net.IPv4Mask,
		"IPv4allrouter":              net.IPv4allrouter,
		"IPv4allsys":                 net.IPv4allsys,
		"IPv4bcast":                  net.IPv4bcast,
		"IPv4len":                    net.IPv4len,
		"IPv4zero":                   net.IPv4zero,
		"IPv6interfacelocalallnodes": net.IPv6interfacelocalallnodes,
		"IPv6len":                    net.IPv6len,
		"IPv6linklocalallnodes":      net.IPv6linklocalallnodes,
		"IPv6linklocalallrouters":    net.IPv6linklocalallrouters,
		"IPv6loopback":               net.IPv6loopback,
		"IPv6unspecified":            net.IPv6unspecified,
		"IPv6zero":                   net.IPv6zero,
		"InterfaceAddrs":             net.InterfaceAddrs,
		"InterfaceByIndex":           net.InterfaceByIndex,
		"InterfaceByName":            net.InterfaceByName,
		"Interfaces":                 net.Interfaces,
		"JoinHostPort":               net.JoinHostPort,
		"Listen":                     net.Listen,
		"ListenIP":                   net.ListenIP,
		"ListenMulticastUDP":         net.ListenMulticastUDP,
		"ListenPacket":               net.ListenPacket,
		"ListenTCP":                  net.ListenTCP,
		"ListenUDP":                  net.ListenUDP,
		"ListenUnix":                 net.ListenUnix,
		"ListenUnixgram":             net.ListenUnixgram,
		"LookupAddr":                 net.LookupAddr,
		"LookupCNAME":                net.LookupCNAME,
		"LookupHost":                 net.LookupHost,
		"LookupIP":                   net.LookupIP,
		"LookupMX":                   net.LookupMX,
		"LookupNS":                   net.LookupNS,
		"LookupPort":                 net.LookupPort,
		"LookupSRV":                  net.LookupSRV,
		"LookupTXT":                  net.LookupTXT,
		"ParseCIDR":                  net.ParseCIDR,
		"ParseIP":                    net.ParseIP,
		"ParseMAC":                   net.ParseMAC,
		"Pipe":                       net.Pipe,
		"ResolveIPAddr":              net.ResolveIPAddr,
		"ResolveTCPAddr":             net.ResolveTCPAddr,
		"ResolveUDPAddr":             net.ResolveUDPAddr,
		"ResolveUnixAddr":            net.ResolveUnixAddr,
		"SplitHostPort":              net.SplitHostPort,
	}
}
