package packages

import (
	"os"
	"reflect"
)

func init() {
	Packages["os"] = map[string]interface{}{
		"Args":              os.Args,
		"Chdir":             os.Chdir,
		"Chmod":             os.Chmod,
		"Chown":             os.Chown,
		"Chtimes":           os.Chtimes,
		"Clearenv":          os.Clearenv,
		"Create":            os.Create,
		"DevNull":           os.DevNull,
		"Environ":           os.Environ,
		"ErrExist":          os.ErrExist,
		"ErrInvalid":        os.ErrInvalid,
		"ErrNotExist":       os.ErrNotExist,
		"ErrPermission":     os.ErrPermission,
		"Exit":              os.Exit,
		"Expand":            os.Expand,
		"ExpandEnv":         os.ExpandEnv,
		"FindProcess":       os.FindProcess,
		"Getegid":           os.Getegid,
		"Getenv":            os.Getenv,
		"Geteuid":           os.Geteuid,
		"Getgid":            os.Getgid,
		"Getgroups":         os.Getgroups,
		"Getpagesize":       os.Getpagesize,
		"Getpid":            os.Getpid,
		"Getuid":            os.Getuid,
		"Getwd":             os.Getwd,
		"Hostname":          os.Hostname,
		"Interrupt":         os.Interrupt,
		"IsExist":           os.IsExist,
		"IsNotExist":        os.IsNotExist,
		"IsPathSeparator":   os.IsPathSeparator,
		"IsPermission":      os.IsPermission,
		"Kill":              os.Kill,
		"Lchown":            os.Lchown,
		"Link":              os.Link,
		"Lstat":             os.Lstat,
		"Mkdir":             os.Mkdir,
		"MkdirAll":          os.MkdirAll,
		"ModeAppend":        os.ModeAppend,
		"ModeCharDevice":    os.ModeCharDevice,
		"ModeDevice":        os.ModeDevice,
		"ModeDir":           os.ModeDir,
		"ModeExclusive":     os.ModeExclusive,
		"ModeNamedPipe":     os.ModeNamedPipe,
		"ModePerm":          os.ModePerm,
		"ModeSetgid":        os.ModeSetgid,
		"ModeSetuid":        os.ModeSetuid,
		"ModeSocket":        os.ModeSocket,
		"ModeSticky":        os.ModeSticky,
		"ModeSymlink":       os.ModeSymlink,
		"ModeTemporary":     os.ModeTemporary,
		"ModeType":          os.ModeType,
		"NewFile":           os.NewFile,
		"NewSyscallError":   os.NewSyscallError,
		"O_APPEND":          os.O_APPEND,
		"O_CREATE":          os.O_CREATE,
		"O_EXCL":            os.O_EXCL,
		"O_RDONLY":          os.O_RDONLY,
		"O_RDWR":            os.O_RDWR,
		"O_SYNC":            os.O_SYNC,
		"O_TRUNC":           os.O_TRUNC,
		"O_WRONLY":          os.O_WRONLY,
		"Open":              os.Open,
		"OpenFile":          os.OpenFile,
		"PathListSeparator": os.PathListSeparator,
		"PathSeparator":     os.PathSeparator,
		"Pipe":              os.Pipe,
		"Readlink":          os.Readlink,
		"Remove":            os.Remove,
		"RemoveAll":         os.RemoveAll,
		"Rename":            os.Rename,
		"SEEK_CUR":          os.SEEK_CUR,
		"SEEK_END":          os.SEEK_END,
		"SEEK_SET":          os.SEEK_SET,
		"SameFile":          os.SameFile,
		"Setenv":            os.Setenv,
		"StartProcess":      os.StartProcess,
		"Stat":              os.Stat,
		"Stderr":            os.Stderr,
		"Stdin":             os.Stdin,
		"Stdout":            os.Stdout,
		"Symlink":           os.Symlink,
		"TempDir":           os.TempDir,
		"Truncate":          os.Truncate,
	}
	var signal os.Signal
	PackageTypes["os"] = map[string]interface{}{
		"Signal": reflect.TypeOf(&signal).Elem(),
	}
	osNotAppEngine()
}
